# Generated by Django 2.2.24 on 2025-03-25 03:45

from django.db import migrations


from django.db import migrations


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    
    flats = Flat.objects.all()
    for flat in flats:
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
        elif flat.construction_year and flat.construction_year < 2015:
            flat.new_building = False
        else:
            flat.new_building = None  
        flat.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]