# Generated by Django 4.2.20 on 2025-03-25 05:35

from django.db import migrations
import phonenumbers

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.filter(owners_phonenumber='+70000000000'):
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(phone_number):
                flat.owner_pure_phone = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
                flat.save()
        except phonenumbers.phonenumberutil.NumberParseException:
            pass

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_complaint_id_and_more'),
    ]


    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
