# Generated by Django 4.2.20 on 2025-03-25 05:35

from django.db import migrations
from phonenumbers import parse, is_valid_number, format_number, PhoneNumberFormat, NumberParseException

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.exclude(owners_phonenumber='').iterator()

    for flat in flats:
        try:
            phone_number = parse(flat.owners_phonenumber, 'RU')
            if is_valid_number(phone_number):
                flat.owner_pure_phone = format_number(phone_number, PhoneNumberFormat.INTERNATIONAL)
                flat.save()
        except NumberParseException:
            continue

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
