# Generated by Django 4.2.20 on 2025-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_normalize_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО собственника')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон собственника')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email собственника')),
                ('flats', models.ManyToManyField(blank=True, related_name='owners', to='property.flat')),
            ],
        ),
    ]
