# Generated by Django 4.2.20 on 2025-03-25 06:02

from django.db import migrations

def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        if flat.owner:
            owner, created = Owner.objects.get_or_create(
                name=flat.owner,
                phone=flat.owners_phonenumber, 
                email=None  
            )

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_normalize_phone_numbers'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
