# Generated by Django 4.2.20 on 2025-03-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
        ('property', '0010_transfer_owners_to_new_model'),
    ]

    operations = [
    ]
