# Generated by Django 4.2.20 on 2025-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_merge_0009_owner_0010_transfer_owners_to_new_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='owner_deprecated',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='flats_as_owner', to='property.owner'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owned_flats',
            field=models.ManyToManyField(blank=True, related_name='flats_owned_by_owner', to='property.flat'),
        ),
    ]
