# Generated by Django 4.2.20 on 2025-04-03 03:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='неизвестно', max_length=128, region='RU', verbose_name='Телефон владельца'),
            preserve_default=False,
        ),
    ]
