# Generated by Django 4.2.20 on 2025-04-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_owner_phone_alter_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(blank=True, default=False, verbose_name='Есть балкон'),
            preserve_default=False,
        ),
    ]
